### ISSUE TITLE
Installation instructions unclear???

### ISSUE THREAD

**Issue by samuelrawrs** [gongahkia/gitfetch#1]
https://github.com/gongahkia/gitfetch/blob/a0825f6f5e0bf95af9e31f86bc2109bcc294b79d/README.md?plain=1#L28-L43

very cool project but why are the installations exactly the same 🤔🤔🤔🤔🤔 sus

**Comment by samuelrawrs** [comment]
Oh gosh I just noticed... is it the $ and > sign.....

**Comment by samuelrawrs** [comment]
ok I noticed this doesn't scale to the window THOUGH hmmm

![image](https://github.com/gongahkia/gitfetch/assets/54682777/51a4fdb6-7405-4255-b78c-4cc0104dbbaa)

**Comment by gongahkia** [comment]
yes unfortunately i didnt know how to do that back then HAHHA i think size 10 is the best

**Comment by gongahkia** [comment]
could probably redo this in curses in a single .py file instead of the spaghett it currently is

**Comment by gongahkia** [comment]
ok you got me there I just tested out this install on fedora and there's some issues obv cuz file structure is different and I realised I failed to account for any other distros minus Debian Ubuntu fedora so gentoo and Manjaro etc all lack support that's my bad.

**Comment by gongahkia** [comment]
ok u no respond so all good bye bye i will redo ok bye bye

**Comment by samuelrawrs** [comment]
WHAT SORRY
